### ISSUE TITLE
version update?

### ISSUE THREAD

**Issue by iovmatrix** [HarukaMa/aleo-pool-server#20]
error[E0599]: no variant or associated item named `VERSION` found for enum `snarkos_node_router_messages::Message` in the current scope
   --> src/prover_peer.rs:136:54
    |
136 | ...                   version: SnarkOSMessage::VERSION,
    |                                                ^^^^^^^ variant or associated item not found in `Message<MainnetV0>`
    |
help: there is an associated constant `VERSIONS` with a similar name
    |
136 |                             version: SnarkOSMessage::VERSIONS,

This occured when updating to 3.7.1...   Any advice

**Comment by iovmatrix** [comment]
i got it to build   buttt now this ?

what info would you like ?

ass@ass-QEMU-Virtual-Machine:~/aleo-pool-server$ ./target/release/aleo-pool-server   --address aleo18k0zd4yl25sfmxl2hjdlff5020xwarrzhp0tnd2ack0r59979yfq60j98a   --port 3032   --api-port 8080 --node 127.0.0.1:4130 -e aleoscan.io
2025-06-02T04:11:43.461537Z  INFO aleo_pool_server::server: Listening on 0.0.0.0:3032

thread 'tokio-runtime-worker' panicked at src/prover_peer.rs:80:68:
called `Result::unwrap()` on an `Err` value: Invalid block metadata: {"network":0,"round":0,"height":0,"cumulative_weight":"0","cumulative_proof_target":"0","coinbase_target":536870911,"proof_target":134217728,"last_coinbase_target":536870911,"last_coinbase_timestamp":1725462000,"timestamp":1725462000}
2025-06-02T04:11:43.490638Z  INFO aleo_pool_server::api: Starting API server on port 8080
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C2025-06-02T04:12:27.116125Z  INFO aleo_pool_server: Received signal: 2
2025-06-02T04:12:27.116156Z  INFO aleo_pool_server: Saving states before exiting...

**Comment by HarukaMa** [comment]
I currently don't have any capacity to work on projects besides my work (which is not crypto related). I'm only keeping the explorer on maintenance mode right now.
